
CREATE TABLE IF NOT EXISTS dicole_domain (
  domain_id         %%INCREMENT%%,
  domain_name       text,
  logo_image        text,
  theme_id          int unsigned default 0,
  default_language  text,
  default_timezone  text,
  localization_namespace text,
  navi_action       text,
  new_user_action   text,
  url_after_logout  text,
  url_after_login   text,
  external_auth     text,
  c_number          text,
  c_organization    text,
  c_address         text,
  c_contact         text,
  c_phone           text,
  c_ident           text,
  c_email           text,
  c_postal_num      text,
  c_city            text,
  c_country         text,
  c_services        text,
  c_last_payment    bigint unsigned,
  unique            ( domain_id ),
  primary key       ( domain_id )
)
