CREATE TABLE IF NOT EXISTS dicole_externalsource (
 id             %%INCREMENT%%,
 name           varchar(64) not null,
 navid          text not null,
 navigation_type text not null,
 url            text not null,
 package        text not null,
 request        varchar(10) not null,
 parameters     text,
 parameters_from_request     text,
 secure         text,
 pass_field     varchar(30),
 user_field     varchar(30),
 use_login_pass int unsigned default 0,
 use_login_user int unsigned default 0,
 custom_object  text,
 custom_obj_id  tinytext,
 custom_where   text,
 custom_fields  text,
 groups_ids     text not null default '',
 users_ids     text not null default '',
 external_type  tinyint unsigned,
 primary key    ( id ),
 unique     ( id ),
 key            ( name )
)
