=head1 NAME

Dicole - Dicole and Dicole API toolkit for creating highly dynamic websites

=head1 DESCRIPTION

Dicole is an OpenInteract2 based application platform for creating
highly dynamic websites with transparent input/output handling,
navigation, group system, generic application features and more.

=head1 COPYRIGHT

Copyright (c) 2003-2004 Ionstream Oy / Dicole.
All rights reserved.

=head1 AUTHORS

Dicole E<lt>info@dicole.comE<gt>
