CREATE TABLE dicole_feeds_items (
 item_id            %%INCREMENT%%,
 feed_id            int unsigned not null,
 date               bigint unsigned not null,
 link		    text,
 title              text,
 content            text,
 enclosure          text,
 enclosure_type	    text,
 category           text,
 comments           text,
 author             text,
 guid               text,
 source             text,
 subject	    text,
 publisher          text,
 description        text,
 contributor        text,
 type               text,
 format             text,
 identifier         text,
 language           text,
 relation           text,
 coverage           text,
 rights             text,
 unique             ( item_id ),
 primary key        ( item_id )
)
