CREATE TABLE dicole_feeds (
 feed_id            %%INCREMENT%%,
 title              text,
 url                text,
 web_link           text,
 description        text,
 copyright          text,
 language           varchar(10),
 image_link         text,
 image_title        text,
 image_url          text,
 icon               text,
 cc_license_url     text,
 generator          text,
 skip_time          bigint unsigned,
 managing_editor    text,
 webmaster          text,
 version            varchar(10),
 updated            bigint unsigned,
 latest_item_date   bigint unsigned,
 number_of_items    int unsigned default 0,
 observers          int unsigned default 0,
 unique             ( feed_id ),
 primary key        ( feed_id )
)
