CREATE TABLE IF NOT EXISTS dicole_feeds_items (
 item_id            %%INCREMENT%%,
 feed_id            int unsigned not null,
 first_fetch_date   bigint unsigned not null,
 last_update_date   bigint unsigned not null,
 date               bigint unsigned not null,
 uid_hash           text,
 content_hash       text,
 link               text,
 title              text,
 content            text,
 enclosure          text,
 enclosure_type	    text,
 category           text,
 comments           text,
 author             text,
 guid               text,
 source             text,
 subject            text,
 publisher          text,
 description        text,
 contributor        text,
 type               text,
 format             text,
 identifier         text,
 language           text,
 relation           text,
 coverage           text,
 rights             text,
 unique             ( item_id ),
 primary key        ( item_id ),
 key                ( first_fetch_date ),
 key                ( feed_id )
)
