CREATE TABLE IF NOT EXISTS dicole_feeds (
 feed_id            %%INCREMENT%%,
 title              text,
 url                text,
 web_link           text,
 description        text,
 copyright          text,
 language           varchar(10),
 image_link         text,
 image_title        text,
 image_url          text,
 icon               text,
 cc_license_url     text,
 generator          text,
 skip_time          bigint unsigned,
 managing_editor    text,
 webmaster          text,
 version            varchar(10),
 updated            bigint unsigned not null default 0,
 latest_item_date   bigint unsigned not null default 0,
 next_update        bigint unsigned not null default 0,
 failed_attempts    int unsigned not null default 0,
 update_interval    int unsigned not null default 3600,
 number_of_items    int unsigned not null default 0,
 observers          int unsigned not null default 0,
 unique             ( feed_id ),
 primary key        ( feed_id ),
 key                ( next_update )
)
