CREATE TABLE IF NOT EXISTS sys_user (
 user_id              %%INCREMENT%%,
 login_name           varchar(25) not null,
 password             varchar(30) not null,
 email                varchar(100) not null,
 facebook_user_id     text,
 phone                text,
 last_login           %%DATETIME%% null,
 num_logins           int,
 theme_id             %%INCREMENT_TYPE%% default 1,
 first_name           varchar(50),
 middle_name          varchar(50),
 last_name            varchar(50),
 name                 varchar(150),
 title                varchar(50),
 language             varchar(6) null,
 inv_secret           text,
 notes                mediumtext,
 removal_date         %%DATETIME%% null,
 timezone             tinytext,
 starting_page        int unsigned,
 dicole_theme         int unsigned,
 incomplete           int unsigned,
 login_disabled       int unsigned,
 external_auth        text,
 latest_activity      bigint unsigned default 0,
 custom_starting_page text,
 primary key          ( user_id )
)
