CREATE TABLE IF NOT EXISTS dicole_presentations_prese (
  prese_id      %%INCREMENT%%,
  group_id      int unsigned not null,
  creator_id    int unsigned not null,
  creation_date bigint unsigned not null,
  featured_date bigint unsigned not null,
  rating        int not null,
  rating_count  int not null,
  name          text,
  description   text,
  prese_type    text,
  url           text,
  embed         text,
  attachment_id text,
  image         text,
  presenter     text,
  duration      text,
  scribd_id		text,
  scribd_key	text,
  scribd_fail   int,
  notes         mediumtext,
  unique        ( prese_id ),
  primary key   ( prese_id ),
  key           ( group_id, creation_date ),
  key           ( group_id, rating )
)
